title: Powering a Raspberry Pi Pico with AA batteries
hero_image: images/banner.png
description: power-pico-aa description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-07"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
